<a href="https://colab.research.google.com/github/fahimaislam2022/Python-/blob/main/1_NumPy_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install numpy

In [2]:
import numpy as np

In [5]:
vector = np.array([1, 2, 3, 4])
print("Vector: {}".format(vector))
print("Shape: {}".format(vector.shape))
print("Dim: {}".format(vector.ndim))
print("Data type: {}".format(vector.dtype))

Vector: [1 2 3 4]
Shape: (4,)
Dim: 1
Data type: int64


The number of dimensions numpy uses is as follows:

`(depth, rows, columns) `

In [6]:
v = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
v.shape = (2, 3, 2)
v

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [7]:
v = np.zeros((2, 3, 2))
v

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

## arange

In [8]:
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [10]:
print("Zeros")
a = np.zeros((3, 3))
print("A: {}".format(a))

Zeros
A: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [11]:
b = np.zeros_like(a)
print("B: {}".format(b))

B: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [13]:
print("\nOnes")
a = np.ones((3, 3))
print("A: {}".format(a))


Ones
A: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [14]:
b = np.ones_like(a)
print("B: {}".format(b))

B: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [17]:
print("\nEmpty")
a= np.empty((3, 3))
print("A: {}".format(a))



Empty
A: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [18]:
b = np.empty_like(a)
print("B: {}".format(b))

B: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


## astype one data type to another

In [21]:
a = np.array([1, 2, 3, 4.5, 6.7])
print("A: {}, dtype: {}".format(a, a.dtype))
b = a.astype(np.int64)
print("B: {}, dtype: {}".format(b, b.dtype))

A: [1.  2.  3.  4.5 6.7], dtype: float64
B: [1 2 3 4 6], dtype: int64


## Vectorization and vector-scalar operations

#### Using operations on same sized arrays produce element wise operations.

In [23]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[4, 5, 6], [1, 2, 3]])

c = a + b
c

array([[5, 7, 9],
       [5, 7, 9]])

In [24]:
c = a * b
c

array([[ 4, 10, 18],
       [ 4, 10, 18]])

In [25]:
c = a - b
c

array([[-3, -3, -3],
       [ 3,  3,  3]])

Using scalars with vectors will produce element wise operations

In [26]:
a = 3
b =np.array([[1, 2, 3], [4, 5, 6]])
c = a + b
c

array([[4, 5, 6],
       [7, 8, 9]])

In [27]:
c = a * b
c

array([[ 3,  6,  9],
       [12, 15, 18]])

In [28]:
c = a - b
c

array([[ 2,  1,  0],
       [-1, -2, -3]])

## Slicing

You can slice by following syntax:
```
array[start_index:end_index]
```
For n-dimensional array:
```
array[start_index:end_index, start_index:end_index]
```

In [31]:
a = np.arange(20)
a


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [30]:
a[10:15] = 5
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9,  5,  5,  5,  5,  5, 15, 16,
       17, 18, 19])

sallow copy

In [34]:
a = np.arange(20)
print(a)
b = a[10:15].copy()
b = 5
print(a)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
5


Slicing by `:` will take the entire axis. So:
```
1. arr2d[:, 0]         Will return array of shape (3, )
2. arr2d[:, :1]        Will return array of shape (3, 1)
```

In [35]:
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
arr2d[:, 0]

array([1, 4, 7])

In [36]:
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
arr2d[:, :1]

array([[1],
       [4],
       [7]])

## Boolean indexing
Using boolen indexing, you can use it to filter or check if any entries have any specific values.

In [37]:
a = np.array(["Mayur", "is", "an", "awesome", "coder"])
a == "Mayur"

array([ True, False, False, False, False])

In [39]:
# lists entry where value != "Mayur"
a[~(a == "Mayur")]

array(['is', 'an', 'awesome', 'coder'], dtype='<U7')

__You can use `|` for `or` and `&` for `and` but not Python's `and`, `or` will not work with NumPy's indexing. __

In [40]:
(a == "Mayur") | (a == "coder")

array([ True, False, False, False,  True])

## Fancy indexing
You can index a list to print the array in the given order. For instance, you want to print the 1st row, 3rd row, and 2nd row in that order.


In [41]:
a = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3], [4, 4, 4]])
a

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [42]:
a[[1, 3, 2]]

array([[2, 2, 2],
       [4, 4, 4],
       [3, 3, 3]])

## Transposing

You can obtains the transpose of your matring using `matrix.T` where `matrix` is your matrix name.

In [43]:
a = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3], [4, 4, 4]])
a.T

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

## Universal Functions
NumPy has variety of functions that can be applied to scalars as well as vectors. Some examples are sqrt, exp, log, log10, sin, cos, arcsin etc.

In [45]:
a = 20
b = np.random.rand(2, 2)
print(np.exp(a))
print(np.exp(b))

485165195.4097903
[[1.62496307 1.17304433]
 [2.35388977 1.27129804]]


## meshgrid

One of the most useful function is meshgrid. It's used to visualize data boundaries of your classifier. What you do is train your classifier, then create a meshgrid of every pixel in the plot, and then classify the pixel. When you give the pixel a specific color according to the labelled class you can clearly visualize the boundaries.

Using meshgrid requires three steps.
1. Create xs (1D array)
2. Create ys (1D array)
3. Create meshgrid (2D array) which corresponds to every pixel in the graph.  

In [49]:
xs = np.linspace(1, 10, 100)
ys = np.linspace(1, 10, 100)
xx, yy = np.meshgrid(xs, ys)
print(xx)
print(yy)


[[ 1.          1.09090909  1.18181818 ...  9.81818182  9.90909091
  10.        ]
 [ 1.          1.09090909  1.18181818 ...  9.81818182  9.90909091
  10.        ]
 [ 1.          1.09090909  1.18181818 ...  9.81818182  9.90909091
  10.        ]
 ...
 [ 1.          1.09090909  1.18181818 ...  9.81818182  9.90909091
  10.        ]
 [ 1.          1.09090909  1.18181818 ...  9.81818182  9.90909091
  10.        ]
 [ 1.          1.09090909  1.18181818 ...  9.81818182  9.90909091
  10.        ]]
[[ 1.          1.          1.         ...  1.          1.
   1.        ]
 [ 1.09090909  1.09090909  1.09090909 ...  1.09090909  1.09090909
   1.09090909]
 [ 1.18181818  1.18181818  1.18181818 ...  1.18181818  1.18181818
   1.18181818]
 ...
 [ 9.81818182  9.81818182  9.81818182 ...  9.81818182  9.81818182
   9.81818182]
 [ 9.90909091  9.90909091  9.90909091 ...  9.90909091  9.90909091
   9.90909091]
 [10.         10.         10.         ... 10.         10.
  10.        ]]


# where
if you have 3 arrays x, y, and condition then, `np.where` is replacement for using:
```
if condition:
    use x
else:
    use y
```

In [50]:
a = [0, -1, 2, 3, -4, -5]
b = [9, 3, 4, 11, 2, 3]
c = [True, False, True,True, False, True]
np.where(c, a, b)

array([ 0,  3,  2,  3,  2, -5])

## mean, sum, std
NumPy provides variety of functions for statistical use. You can furthermore specify the axis you want to reduce.

In [51]:
a = np.random.rand(3, 3)
print(a)
print(np.mean(a))
print(a.mean())
print(np.std(a))

[[0.65683215 0.16868737 0.21901792]
 [0.5299343  0.4797558  0.59160472]
 [0.57238589 0.56126119 0.72785567]]
0.500815000734293
0.500815000734293
0.17761303251486446
